-------------------
-- CRIAÇÃO DO BD --
-------------------

--Tabela Aldeia
CREATE TABLE ALDEIA(NOME VARCHAR(20) PRIMARY KEY);

--Tabela Ninja
CREATE TABLE NINJA(
  RG_NINJA VARCHAR(9), 
  NOME_CLA VARCHAR(20), 
  NOME VARCHAR (20),
  NOME_ALDEIA VARCHAR(20),
  PRIMARY KEY (RG_NINJA),
  FOREIGN KEY (NOME_ALDEIA) REFERENCES ALDEIA(NOME)
);

CREATE TABLE RIVALIDADE (
  RG_NINJA VARCHAR(9),
  RG_RIVAL VARCHAR(9),
  PRIMARY KEY (RG_NINJA, RG_RIVAL),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA),
  FOREIGN KEY (RG_RIVAL) REFERENCES NINJA(RG_NINJA)
);

CREATE TYPE RANK AS ENUM ('D', 'C', 'B', 'A', 'S', 'SS');
CREATE TYPE ELEMENTO AS ENUM (
  'KATON',   -- Fogo
  'SUITON',  -- Água
  'DOTON',   -- Terra
  'FUUTON',  -- Vento
  'RAITON',  -- Raio
  'MOKUTON', -- Madeira
  'YOTON',   -- Lava
  'HYOTON',  -- Gelo
  'RANTON',  -- Tempestade
  'JITON',   -- Magnetismo
  'SHOTON',  -- Cristal
  'FUTTON',  -- Vapor
  'ENTON',   -- Chama negra
  'BAKUTON'  -- Explosão
);

CREATE TABLE JUTSU(
  RG_NINJA VARCHAR(9), 
  NOME VARCHAR (20), 
  ELEMENTO ELEMENTO,
  RANK RANK,
  PRIMARY KEY(RG_NINJA, NOME)
);

--heranças
--TO BE FIXED
CREATE TABLE HOKAGE(
  RG_NINJA VARCHAR(9),
  PRIMARY KEY (RG_NINJA),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA)
);

CREATE TABLE JOUNIN(
  RG_NINJA VARCHAR(9),
  PRIMARY KEY (RG_NINJA),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA)
);

CREATE TABLE CHUNNIN(
  RG_NINJA VARCHAR(9),
  PRIMARY KEY (RG_NINJA),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA)
);

CREATE TABLE GENNIN(
  RG_NINJA VARCHAR(9),
  PRIMARY KEY (RG_NINJA),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA)
);

-- Tabela equipe
CREATE TABLE EQUIPE(NUMERO INTEGER PRIMARY KEY);

-- Tabelas de entidade fraca
CREATE TABLE MISSAO(
  EQUIPE INTEGER,
  DATA_FINALIZACAO DATE,
  RANK RANK,
  RECOMPENSA NUMERIC(10,2),
  DESCRICAO VARCHAR(300),
  PRIMARY KEY (EQUIPE, DATA_FINALIZACAO),
  FOREIGN KEY (EQUIPE) REFERENCES EQUIPE(NUMERO)
);

CREATE TABLE EXAME_CHUNNIN(
  ALDEIA VARCHAR(20),
  DATA_INICIO DATE,
  PRIMARY KEY (ALDEIA, DATA_INICIO),
  FOREIGN KEY (ALDEIA) REFERENCES ALDEIA(NOME)
);


-- tabela de relações N:N
CREATE TABLE JOUNIN_AVALIA_GENNIN(
  RG_NINJA_AVALIADO VARCHAR(9),
  RG_NINJA_AVALIADOR VARCHAR(9),
  MISSAO_EQUIPE INTEGER,
  DATA_FINALIZACAO_EQUIPE DATE,
  PRIMARY KEY (RG_NINJA_AVALIADO, RG_NINJA_AVALIADOR, MISSAO_EQUIPE, DATA_FINALIZACAO_EQUIPE),
  FOREIGN KEY (RG_NINJA_AVALIADO) REFERENCES GENNIN(RG_NINJA),
  FOREIGN KEY (RG_NINJA_AVALIADOR) REFERENCES JOUNIN(RG_NINJA),
  FOREIGN KEY (MISSAO_EQUIPE, DATA_FINALIZACAO_EQUIPE) REFERENCES MISSAO(EQUIPE, DATA_FINALIZACAO)
);

CREATE TABLE NINJA_COMPOE_EQUIPE(
  RG_NINJA VARCHAR(9),
  MISSAO_EQUIPE INTEGER,
  MISSAO_DATA_FINALIZACAO DATE,
  PRIMARY KEY (RG_NINJA, MISSAO_EQUIPE, MISSAO_DATA_FINALIZACAO),
  FOREIGN KEY (RG_NINJA) REFERENCES NINJA(RG_NINJA),
  FOREIGN KEY (MISSAO_EQUIPE, MISSAO_DATA_FINALIZACAO) REFERENCES MISSAO(EQUIPE, DATA_FINALIZACAO)
);

--tabela associativa
CREATE TABLE PARTICIPA(
  RG_JOUNIN_AVALIADOR VARCHAR(9),
  RG_GENNIN_EXAMINADO VARCHAR(9),
  EXAME_CHUNNIN_ALDEIA VARCHAR(20),
  EXAME_CHUNNIN_DATA_INICIO DATE,
  PRIMARY KEY(RG_GENNIN_EXAMINADO,RG_JOUNIN_AVALIADOR,EXAME_CHUNNIN_ALDEIA,EXAME_CHUNNIN_DATA_INICIO),
  FOREIGN KEY (RG_JOUNIN_AVALIADOR) REFERENCES JOUNIN(RG_NINJA),
  FOREIGN KEY (RG_GENNIN_EXAMINADO) REFERENCES GENNIN(RG_NINJA),
  FOREIGN KEY (EXAME_CHUNNIN_ALDEIA, EXAME_CHUNNIN_DATA_INICIO) REFERENCES EXAME_CHUNNIN(ALDEIA, DATA_INICIO)
);